function [nodes_file, cells_file, bc_files] = mesh_case_paths(nnodes)
    %MESH_CASE_PATHS Return mesh file paths for a given 1D mesh size.

    suffix = sprintf('1D_%dnodes', nnodes);

    nodes_file = ['Meshes/coords_' suffix '.dat'];
    cells_file = ['Meshes/cells_' suffix '_allsquares_sorted.dat'];

    bc_files = { ...
                    ['Meshes/bc_bottom_' suffix '.dat'], ...
                    ['Meshes/bc_left_' suffix '.dat'], ...
                    ['Meshes/bc_right_' suffix '.dat'], ...
                    ['Meshes/bc_top_' suffix '.dat'], ...
                    ['Meshes/bc_whole_contour_' suffix '.dat'] ...
                };
end
