classdef FilePaths

    properties (Constant)
        NODES = 'L_grid/nodes_L_1.dat';
        CELLS = 'L_grid/cells_L_1.dat';
        BOUNDARY_CONDITIONS = { ...
                                   'L_grid/bc_L_1_1.dat', ...
                                   'L_grid/bc_L_1_2.dat', ...
                                   'L_grid/bc_L_1_3.dat', ...
                                   'L_grid/bc_L_1_4.dat', ...
                                   'L_grid/bc_L_1_5.dat', ...
                                   'L_grid/bc_L_1_6.dat', ...
                                   'L_grid/bc_L_1_7.dat'
                               };
    end

end
