function next_vertex_index = get_next_vertex_index( ...
        current_vertex_index, ...
        vertices_total_number ...
    )
    next_vertex_index = mod(current_vertex_index, vertices_total_number) + 1;
end
