function vector_to_next_vertex = get_vector_to_next_vertex( ...
        polygon_nodes, ...
        current_vertex_index, ...
        vertices_total_number ...
    )
    next_vertex_index = get_next_vertex_index( ...
        current_vertex_index, ...
        vertices_total_number ...
    );
    vector_to_next_vertex = ...
        polygon_nodes(next_vertex_index, :) - polygon_nodes(current_vertex_index, :);
end
