function [left_face_velocity, right_face_velocity] = get_velocity_at_faces( ...
        cell_velocity, ...
        left_neighbour_velocity, ...
        right_neighbour_velocity ...
    )

    left_face_velocity = (left_neighbour_velocity + cell_velocity) / 2;
    right_face_velocity = (right_neighbour_velocity + cell_velocity) / 2;
end
