function cells = process_mesh_geometry( ...
        nodes_data, ...
        cells_data, ...
        bcs_data ...
    )

    % initialize the cells vector
    num_cells = length(cells_data);
    cell_data = struct( ...
        'nodes', [], ...
        'faces', [], ...
        'volume', 0, ...
        'centroid', [0, 0], ...
        'area', [], ...
        'normals', [0, 0] ...
    );
    cells = repmat(cell_data, 1, num_cells);

    for cell_index = 1:num_cells

        % try
        % Process the data of one single cell and save it in mesh_data.
        process_cell(cells_data{cell_index}, nodes_data);
        cells(cell_index) = process_cell(cells_data{cell_index}, nodes_data);
        % catch exception
        %     msg = sprintf('In cell number %d:\n  %s', ...
        %         cell_index, exception.message);
        %     throw(MException('Simulator:MeshProcessorError', msg));
        % end

    end

end
